version: 2
jobs:

  #TODO: Use 'persist_to_workspace' to reduce duplication

  html5-3.2:
    docker:
     - image: openfl/openfl-tests-unit-3.2:0.0.1
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime create TextRendering
     - run: haxelib run lime build HelloWorld html5
     - run: haxelib run lime build SimpleAudio html5
     - run: haxelib run lime build SimpleImage html5

  neko-3.2:
    docker:
     - image: openfl/openfl-tests-unit-3.2:0.0.1
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: haxelib run lime rebuild linux -release -64 -nocffi
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime create TextRendering
     - run: haxelib run lime build HelloWorld neko
     - run: haxelib run lime build SimpleAudio neko
     - run: haxelib run lime build SimpleImage neko

  cpp-3.2:
    docker:
     - image: openfl/openfl-tests-unit-3.2:0.0.1
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: haxelib run lime rebuild linux -release -64 -nocffi
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime create TextRendering
     - run: haxelib run lime build HelloWorld linux
     - run: haxelib run lime build SimpleAudio linux
     - run: haxelib run lime build SimpleImage linux
  
  flash-3.2:
    docker:
     - image: openfl/openfl-tests-unit-3.2:0.0.1
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime create TextRendering
     - run: haxelib run lime build HelloWorld flash
     - run: haxelib run lime build SimpleAudio flash
     - run: haxelib run lime build SimpleImage flash
  
  docs-3.2:
    docker:
     - image: openfl/openfl-tests-unit-3.2:0.0.1
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: git clone https://github.com/openfl/dox ~/dox --depth 1
     - run: haxelib dev dox ~/dox
     - run: cd ~/project/docs && haxe build.hxml

######

  html5-3.4:
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime create TextRendering
     - run: haxelib run lime build HelloWorld html5
     - run: haxelib run lime build SimpleAudio html5
     - run: haxelib run lime build SimpleImage html5

  neko-3.4:
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: haxelib run lime rebuild linux -release -64 -nocffi
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime create TextRendering
     - run: haxelib run lime build HelloWorld neko
     - run: haxelib run lime build SimpleAudio neko
     - run: haxelib run lime build SimpleImage neko

  cpp-3.4:
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: haxelib run lime rebuild linux -release -64 -nocffi
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime create TextRendering
     - run: haxelib run lime build HelloWorld linux
     - run: haxelib run lime build SimpleAudio linux
     - run: haxelib run lime build SimpleImage linux
  
  flash-3.4:
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: haxelib run lime rebuild tools -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime create TextRendering
     - run: haxelib run lime build HelloWorld flash
     - run: haxelib run lime build SimpleAudio flash
     - run: haxelib run lime build SimpleImage flash
  
  docs-3.4:
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - checkout
     - run:
        name: Setup Lime dev directory
        command: haxelib dev lime ~/project
     - run: git clone https://github.com/openfl/dox ~/dox --depth 1
     - run: haxelib dev dox ~/dox
     - run: cd ~/project/docs && haxe build.hxml

workflows:
  version: 2
  haxe-3.2:
    jobs:
     - html5-3.2
     - neko-3.2
     - cpp-3.2
     - flash-3.2
     - docs-3.2
  haxe-3.4:
    jobs:
     - html5-3.4
     - neko-3.4
     - cpp-3.4
     - flash-3.4
     - docs-3.4